const iso2region = {
    AF: 'Asia',
    AX: 'Europe',
    AL: 'Europe',
    DZ: 'Other',
    AS: 'Other',
    AD: 'Europe',
    AO: 'Other',
    AI: 'Other',
    AQ: 'Other',
    AG: 'Other',
    AR: 'Other',
    AM: 'Asia',
    AW: 'Other',
    AU: 'Other',
    AT: 'Europe',
    AZ: 'Asia',
    BS: 'Other',
    BH: 'Asia',
    BD: 'Asia',
    BB: 'Other',
    BY: 'Europe',
    BE: 'Europe',
    BZ: 'Other',
    BJ: 'Other',
    BM: 'North America',
    BT: 'Asia',
    BO: 'Other',
    BQ: 'Other',
    BA: 'Europe',
    BW: 'Other',
    BV: 'Other',
    BR: 'Other',
    IO: 'Other',
    BN: 'Asia',
    BG: 'Europe',
    BF: 'Other',
    BI: 'Other',
    CV: 'Other',
    KH: 'Asia',
    CM: 'Other',
    CA: 'North America',
    KY: 'Other',
    CF: 'Other',
    TD: 'Other',
    CL: 'Other',
    CN: 'Asia',
    CX: 'Other',
    CC: 'Other',
    CO: 'Other',
    KM: 'Other',
    CG: 'Other',
    CD: 'Other',
    CK: 'Other',
    CR: 'Other',
    CI: 'Other',
    HR: 'Europe',
    CU: 'Other',
    CW: 'Other',
    CY: 'Asia',
    CZ: 'Europe',
    DK: 'Europe',
    DJ: 'Other',
    DM: 'Other',
    DO: 'Other',
    EC: 'Other',
    EG: 'Other',
    SV: 'Other',
    GQ: 'Other',
    ER: 'Other',
    EE: 'Europe',
    SZ: 'Other',
    ET: 'Other',
    FK: 'Other',
    FO: 'Europe',
    FJ: 'Other',
    FI: 'Europe',
    FR: 'Europe',
    GF: 'Other',
    PF: 'Other',
    TF: 'Other',
    GA: 'Other',
    GM: 'Other',
    GE: 'Asia',
    DE: 'Europe',
    GH: 'Other',
    GI: 'Europe',
    GR: 'Europe',
    GL: 'North America',
    GD: 'Other',
    GP: 'Other',
    GU: 'Other',
    GT: 'Other',
    GG: 'Europe',
    GN: 'Other',
    GW: 'Other',
    GY: 'Other',
    HT: 'Other',
    HM: 'Other',
    VA: 'Europe',
    HN: 'Other',
    HK: 'Asia',
    HU: 'Europe',
    IS: 'Europe',
    IN: 'Asia',
    ID: 'Asia',
    IR: 'Asia',
    IQ: 'Asia',
    IE: 'Europe',
    IM: 'Europe',
    IL: 'Asia',
    IT: 'Europe',
    JM: 'Other',
    JP: 'Asia',
    JE: 'Europe',
    JO: 'Asia',
    KZ: 'Asia',
    KE: 'Other',
    KI: 'Other',
    KP: 'Asia',
    KR: 'Asia',
    KW: 'Asia',
    KG: 'Asia',
    LA: 'Asia',
    LV: 'Europe',
    LB: 'Asia',
    LS: 'Other',
    LR: 'Other',
    LY: 'Other',
    LI: 'Europe',
    LT: 'Europe',
    LU: 'Europe',
    MO: 'Asia',
    MG: 'Other',
    MW: 'Other',
    MY: 'Asia',
    MV: 'Asia',
    ML: 'Other',
    MT: 'Europe',
    MH: 'Other',
    MQ: 'Other',
    MR: 'Other',
    MU: 'Other',
    YT: 'Other',
    MX: 'Other',
    FM: 'Other',
    MD: 'Europe',
    MC: 'Europe',
    MN: 'Asia',
    ME: 'Europe',
    MS: 'Other',
    MA: 'Other',
    MZ: 'Other',
    MM: 'Asia',
    NA: 'Other',
    NR: 'Other',
    NP: 'Asia',
    NL: 'Europe',
    NC: 'Other',
    NZ: 'Other',
    NI: 'Other',
    NE: 'Other',
    NG: 'Other',
    NU: 'Other',
    NF: 'Other',
    MK: 'Europe',
    MP: 'Other',
    NO: 'Europe',
    OM: 'Asia',
    PK: 'Asia',
    PW: 'Other',
    PS: 'Asia',
    PA: 'Other',
    PG: 'Other',
    PY: 'Other',
    PE: 'Other',
    PH: 'Asia',
    PN: 'Other',
    PL: 'Europe',
    PT: 'Europe',
    PR: 'Other',
    QA: 'Asia',
    RE: 'Other',
    RO: 'Europe',
    RU: 'Europe',
    RW: 'Other',
    BL: 'Other',
    SH: 'Other',
    KN: 'Other',
    LC: 'Other',
    MF: 'Other',
    PM: 'North America',
    VC: 'Other',
    WS: 'Other',
    SM: 'Europe',
    ST: 'Other',
    SA: 'Asia',
    SN: 'Other',
    RS: 'Europe',
    SC: 'Other',
    SL: 'Other',
    SG: 'Asia',
    SX: 'Other',
    SK: 'Europe',
    SI: 'Europe',
    SB: 'Other',
    SO: 'Other',
    ZA: 'Other',
    GS: 'Other',
    SS: 'Other',
    ES: 'Europe',
    LK: 'Asia',
    SD: 'Other',
    SR: 'Other',
    SJ: 'Europe',
    SE: 'Europe',
    CH: 'Europe',
    SY: 'Asia',
    TW: 'Asia',
    TJ: 'Asia',
    TZ: 'Other',
    TH: 'Asia',
    TL: 'Asia',
    TG: 'Other',
    TK: 'Other',
    TO: 'Other',
    TT: 'Other',
    TN: 'Other',
    TR: 'Asia',
    TM: 'Asia',
    TC: 'Other',
    TV: 'Other',
    UG: 'Other',
    UA: 'Europe',
    AE: 'Asia',
    GB: 'Europe',
    US: 'North America',
    UM: 'Other',
    UY: 'Other',
    UZ: 'Asia',
    VU: 'Other',
    VE: 'Other',
    VN: 'Asia',
    VG: 'Other',
    VI: 'Other',
    WF: 'Other',
    EH: 'Other',
    YE: 'Asia',
    ZM: 'Other',
    ZW: 'Other',
  };

  const Regions = {
    "North America":1, 
    "Europe":2, 
    "Asia":3, 
    "Other":4 
};

function ISOCodeToRegion(isoCode) {
    let region = 'Other';

    if (isoCode) {
        region = iso2region[isoCode];
    }

    if (!region) {
        region = 'Other';
    }

    return Regions[region];
}

module.exports = {
    Regions,
    ISOCodeToRegion
};